spring.application.name=LearningCrud

spring.datasource.url=jdbc:h2:mem:livraria;DB_CLOSE_DELAY=0;DB_CLOSE_ON_EXIT=false;
spring.datasource.hikari.driver=org.h2.Driver
spring.datasource.username=db_livraria
spring.datasource.password=db_livraria

# Configurações do JPA // HIBERNATES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true